package com.sinapsi.android.utils;

import android.content.Context;
import android.content.Intent;

import java.util.HashMap;
import java.util.Map;

/**
 * Utility class to help sending temporary objects across activities/services in the same
 * application via intent and application instance.
 */
public class TempParameterManager{

    public static final String EXTRA_PARAM_KEY = "EXTRA_PARAM_KEY";

    private int paramIdCounter = 0;

    private Map<Integer, Object[]> paramMap = new HashMap<>();

    /**
     * Puts the parameters to a map, which key is autogenerated and added to a new intent
     * instance as extra.
     *
     * @param context the package context for the intent
     * @param target the target class
     * @param parameters the parameters
     * @return a new Intent instance
     */
    public Intent newIntentForTempParameters(Context context, Class<?> target, Object... parameters){
        Intent i = new Intent(context, target);
        paramMap.put(paramIdCounter, parameters);
        i.putExtra(EXTRA_PARAM_KEY, paramIdCounter);
        ++paramIdCounter;
        return i;
    }

    /**
     * todo: doku
     * @param id
     * @return
     */
    public Object[] getTempParameters(Integer id){
        return paramMap.get(id);
    }

    /**
     * todo: doku
     * @param id
     */
    public void removeTempParameters(Integer id){
        paramMap.remove(id);
    }

    /**
     * todo: doku
     * @param id
     * @return
     */
    public Object[] pullTempParameters(Integer id){
        Object[] result = getTempParameters(id);
        removeTempParameters(id);
        return result;
    }

    /**
     * todo: doku
     * @param i
     * @return
     */
    public Object[] getTempParameters(Intent i){
        int id = i.getIntExtra(EXTRA_PARAM_KEY,-1);
        if(id < 0) throw new RuntimeException("The intent has no EXTRA_PARAM_KEY entry.");
        return getTempParameters(id);
    }

    /**
     * todo: doku
     * @param i
     * @return
     */
    public Object[] pullTempParameters(Intent i){
        Object[] result = getTempParameters(i);
        removeTempParameters(i.getIntExtra(EXTRA_PARAM_KEY,-1));
        return result;
    }
}
